// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIBhK-55GIhZLG6-c0sPmHfnTD9Ahsesk',
    appId: '1:423273301098:web:bd1784752e1a0c7b16f613',
    messagingSenderId: '423273301098',
    projectId: 'ccm-web-4cd3d',
    authDomain: 'ccm-web-4cd3d.firebaseapp.com',
    databaseURL: 'https://ccm-web-4cd3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ccm-web-4cd3d.appspot.com',
    measurementId: 'G-86RN73L6XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrEsN7gU7tUK8ktvScwV4HKrYbN6qpBdw',
    appId: '1:423273301098:android:aa9ac6e5d49e750316f613',
    messagingSenderId: '423273301098',
    projectId: 'ccm-web-4cd3d',
    databaseURL: 'https://ccm-web-4cd3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ccm-web-4cd3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARQ9H7yug_AktGt7_HKZzhf_vt5e_QzMw',
    appId: '1:423273301098:ios:98eaa751afe7d70816f613',
    messagingSenderId: '423273301098',
    projectId: 'ccm-web-4cd3d',
    databaseURL: 'https://ccm-web-4cd3d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ccm-web-4cd3d.appspot.com',
    iosClientId: '423273301098-lj6uv4gp6c4u9qmi372f43isg31ngtbk.apps.googleusercontent.com',
    iosBundleId: 'com.digisailor.cwrcloud',
  );
}
